### ISSUE TITLE
Epg url?

### ISSUE THREAD

**Issue by drdedus** [free-greek-iptv/greek-iptv#15]
Καλημέρα με υγεία.
Υπάρχει κάποιο url να βάλουμε στους player για να έχουμε epg?

**Comment by Twilight0** [comment]
https://github.com/free-greek-iptv/greek-iptv/blob/master/android.m3u#L1

**Comment by drdedus** [comment]
Αυτό ειναι link για epg η ειναι τα κανάλια μαζί με epg?
Δοκίμασα σε perfect player, kodi και αλλο ενα και δεν βγάζω άκρη?
