### ISSUE TITLE
Κενη λιστα!

### ISSUE THREAD

**Issue by pitsi** [free-greek-iptv/greek-iptv#2]
Μετα το χτεσινο commit εδω
https://github.com/free-greek-iptv/greek-iptv/commit/2e2631e07a65df12b5dd11976d60f9b2ff3a94cd
βλεπω πως η λιστα εμεινε εντελως κενη. Εγινε κατα λαθος ή υπαρχει καποιος λογος για αυτο?

**Comment by Twilight0** [comment]
Μπορεί να υπάρχει λόγος που συνέβη αυτό από κάποιον άλλον ιδιοκτήτη του αποθετηρίου.

**Comment by komhsgr** [comment]
ο λογος ειναι απλος, με βριζουν και απαιτουν συνεχεια σε κατι που τους δινω
εντελως δωρεαν  εφοσον υπαρχει τοση αχαριστια ας πανε να πληρωσουν
συνδρομιτικη τηλεοραση και εκει ας απαιτουν και ας βριζουν εγω σταματαω

2018-02-16 15:58 GMT+02:00 Twilight0 <notifications@github.com>:

**Comment by upggr** [comment]
This list is maintained by certain individuals totally free with no help or contribution from anyone else and is used by hundreds of paid services for nothing. if you are worried one day it might be blank, you may fork this repository and sync regularly and in the worst case scenario continue updates on your own fork if the owners of this repo decide they no longer want to update it.

**Comment by komhsgr** [comment]
all ok now

2018-02-16 19:21 GMT+02:00 Ioannis Kokkinis <notifications@github.com>:

**Comment by pitsi** [comment]
Θα εκανα fork το repo αν ηξερα πως να βρω τα url απο τα 5-6 καναλια που με ενδιαφερουν.
Αν εχεις τετοια αντιμετωπιση απο καποιους, απλα κοψε τα πολλα καναλια και ασε μονο λιγα και δωρεαν.

Μιας και η λιστα επεστρεψε, το κλεινω το issue.
