### ISSUE TITLE
Skai

### ISSUE THREAD

**Issue by StarWors42** [free-greek-iptv/greek-iptv#24]
Hi guys, SKAI isnt working. It plays nine seconds from my style rocks and restart again. 
My greek wife need to watch BigBrother in germany 😂

**Comment by komhsgr** [comment]
skai tv is from https://www.skaitv.gr/live  and working great

**Comment by StarWors42** [comment]
@komhsgr for me it works for long timewithout issues. Now it didn't work on 2 different apps for two days
Take a look at my video maybe you have a idea to fix it

https://streamable.com/1p7olf

**Comment by komhsgr** [comment]
This is not for my app.  And the stream is for this site https://www.skaitv.gr/live

**Comment by StarWors42** [comment]
#EXTINF:-1 group-title="ΠΑΝΕΛΛΑΔΙΚΑ" tvg-name="Skai" tvg-logo="https://i.imgur.com/xokA84y.png",SKAI HD 
https://skai-live-gr-bb.siliconweb.com/media/cambria4/index.m3u8

Ok i have the link from your android.m3u

**Comment by komhsgr** [comment]
skai have new link plz check it 
https://skai-live-gr-cy.siliconweb.com/media/cambria4/index.m3u8


working fine now?

**Comment by StarWors42** [comment]
For me is offline, or maybe offline again.

**Comment by komhsgr** [comment]
geo block not working to germany maybe

**Comment by StarWors42** [comment]
No i have try it with NordVPN and Greek IP is the same Issue

**Comment by username980** [comment]
SKAI link should be replaced with:
https://skai-live-back.siliconweb.com/media/cambria4/index.m3u8

**Comment by StarWors42** [comment]
> SKAI link should be replaced with:
> https://skai-live-back.siliconweb.com/media/cambria4/index.m3u8

Very nice man, it works. Thank you
