### ISSUE TITLE
Μεταφορα των Vouli και One channel κατω απο τα υπολοιπα της κατηγοριας "Πανελλαδικα"

### ISSUE THREAD

**Issue by pitsi** [free-greek-iptv/greek-iptv#25]
Θα ηθελα να μεταφερθουν τα καναλια Vouli (γραμμες 62 και 63) και One channel (γραμμες 72 και 73) κατω απο τα υπολοιπα της κατηγοριας Πανελλαδικα (γραμμη 1 ως 29).

Ο λογος: Παιρνω καθημερινα τη λιστα με curl και με το sed σβηνω οτι υπαρχει απο τη γραμμη 30 και κατω, μιας και δεν με ενδιαφερουν τα υπολοιπα καναλια. 
```
curl https://raw.githubusercontent.com/free-greek-iptv/greek-iptv/master/android.m3u > /storage/videos/greektv-iptv.m3u
sed -i '30,$d' /storage/videos/greektv-iptv.m3u
```
Αλλα ετσι σβηνονται και αυτα που λεω παραπανω. Οποτε, αν τα μετακινησει καποιος κατω απο την γραμμη 29, θα αλλαξω το sed εκει να σβηνει πχ απο την 33 και μετα.

Ευχαριστω προκαταβολικα.

**Comment by komhsgr** [comment]
Θα στο πω ευγενικα ΑΠΟΚΛΕΙΕΤΑΙ  να κανω αυτο που ζητας σοβαρεψου

**Comment by pitsi** [comment]
Το ξερα :( Θα ψαχτω να κανω το sed να κοβει τα ενδιαμεσα, δεν εχω αλλη επιλογη.

Γιατι ομως αυτα τα 2 εινια χωρια απο τα υπολοιπα? Ξερω πως ενας κανονικος iptv client τα ξεχωριζει ανα γκρουπ, οποτε ayta ta 2 πανε μαζι με τα υπολοιπα στο γκρουπ Πανελλαδικα, ανεξαρτητα απο το που θα ειναι μεσα στη λιστα. Αλλα o iptv client στο kodi δεν με βολευει :(

**Comment by upggr** [comment]
Ρε φιλε, κανε το fork και κανε ότι θελεις

**Comment by pitsi** [comment]
Τελικα ηταν πιο απλο απο οσο νομιζα. Αρχιζοντας απο το τελος
`sed -i '74,$d' android.m3u `
για να φυγουν ολα απο την 74 και κατω
`sed -i '64,71d' android.m3u` 
για να φυγουν ολα απο την 64 ως την 71, βαζοντας μεσα δηλαδη το One tv και τελος ενα
`sed -i '30,61d' android.m3u`
για να φυγουν ολα απο την 30 ως την 61, βαζοντας μεσα και τη Vouli.
