### ISSUE TITLE
Αλαγη διευθυνσης Galaxy gr

### ISSUE THREAD

**Issue by sakhs75** [free-greek-iptv/greek-iptv#28]
https://channel.streams.ovh:1936/galaxygr-1/galaxygr-1/playlist.m3u8

**Comment by Netmaxtv** [comment]
@sakhs75 Καλησπέρα,μπορείς να μου πεις το e-mail σου?

**Comment by komhsgr** [comment]
komhs6@gmail.com

**Comment by Netmaxtv** [comment]
Γιώργο,το email του galaxy θέλω.
