### ISSUE TITLE
SKAI μια ωρα πισω;

### ISSUE THREAD

**Issue by malebuffy** [free-greek-iptv/greek-iptv#29]
Ξερει κανεις γιατι σε εμένα το ΣΚΑΙ είναι ακριβώς μια ώρα πισω;

**Comment by komhsgr** [comment]
το live ειναι απο τον ιδιο το σταθμό  
https://www.skaitv.gr/live

**Comment by demsmoran** [comment]
ERT 1 is often several hours behind (about 3)

**Comment by komhsgr** [comment]
https://www.ertflix.gr/ert1-live/

**Comment by malebuffy** [comment]
Έχει να κάνει με το πρόγραμμα αναπαραγωγής. Όταν βάζω ΣΚΑΙ με το VLC παίζει κανονικά...όταν το βάζω με το Fermata Player το παίζει μια ώρα πίσω, ίσως επειδή είμαι Ελβετία και είμαστε μια ώρα πίσω. Πάντως δεν εχσι σχέση με το λινκ...αφού με το VLC παίζει κανονικά.

**Comment by malebuffy** [comment]
Ήταν το player.
