### ISSUE TITLE
Λογοτυπα που λειπουν και προτεινομενες αλλαγες για να δουλευει το epg σε καποια καναλια

### ISSUE THREAD

**Issue by pitsi** [free-greek-iptv/greek-iptv#38]
Για αρχη, λειπουνε τα λογοτυπα των ant1, alpha και star επειδη το domain στο οποιο αναφερονται (greektv.pbworks.com) δεν υφισταται πλεον. Αν τα εχει καποιος, ας τα ανεβασει στο imgur οπως τα υπολοιπα και ας αλλαχτουν τα url τους. Μπορω να το κανω και εγω αν θελετε, απλα θα παρω τις εικονες απο τις σελιδες των καναλιων ή απο τη wikipedia.

Επισης, δεν δουλευει το epg για τα καναλια mega, ant1, alpha, star και skai, οπως φαινεται στην εικονα
![screenshot001](https://user-images.githubusercontent.com/5880037/117485698-61171500-af71-11eb-8f3c-e4392e7f4663.png)

Θεωρω οτι συμβαινει επειδη τα ονοματα των καναλιων στο πεδιο tvg-name εχουν το id της digea, πχ digea.mega.gr, σε αντιθεση με τα υπολοιπα που εχουν εκει το display name (απο το xml αρχειο που λεω παρακατω για το epg). Αλλαζοντας λοιπον τα ονοματα στα
```
"digea.mega.gr"
"digea.ant1.gr"
"digea.alpha.gr"
"digea.star.gr"
"digea.skai.gr"
```
αντιστοιχα σε
```
"MEGA"
"ANT1"
"ALPHA"
"STAR"
"SKAI"
```
το epg δουλευει κανονικα για ολα, οπως φαινεται εδω
![screenshot002](https://user-images.githubusercontent.com/5880037/117488746-7130f380-af75-11eb-9720-bb10540b576c.png)

Το περιεργο εδω ειναι πως το ert sports δουλευει και με "ert.ertsports.gr" και με "ERT SPORTS" στο συγκεκριμενο πεδιο. Αλλα αφου ολα τα υπολοιπα δουλευουν με το αντιστοιχο display name τους, μπορει να αλλαχτει και αυτο για λογους ομοιομορφιας.

Ολα τα παραπανω εινια απο τον pvr iptv simple client του kodi 18.9 (libreelec 9.2.6) και το epg απο τη γνωστη διευθυνση εδω
`https://github.com/GreekTVApp/epg-greece-cyprus/releases/download/EPG/epg.xml`
Το ιδιο το kodi δεν γουσταρει το συμπιεσμενο αρχειο που ειναι σε .gz, γιαυτο βαζω το url για το ασυμπιεστο.

p.s. Με ενδιαφερουν μονο τα 10 καναλια που ειναι στη λιστα "Πανελλαδικα". Για τα υπολοιπα δεν γνωριζω και δεν θελω να ασχοληθω.

**Comment by pitsi** [comment]
Ευχαριστω για την αμεση αλλαγη στα λογοτυπα που ελειπαν :)
Αν θελετε καποια βοηθεια για το epg, ευχαριστως να το ψαξω περισσοτερο.

**Comment by komhsgr** [comment]
μια χαρα δουλευει το epg δεν το ανακατευω παραπανω

**Comment by pitsi** [comment]
Μπορεις να αναφερεις τι εχεις κανει και σε ποια πλατφορμα/εφαρμογη? 
Στην αναγκη κανω 4-5 sed και τα αλλαζω στο αρχειο που κατεβαινει τοπικα, δεν ειναι προβλημα, αλλα καλυτερα θα ηταν να δουλευε με τον ιδιο τροπο παντου.

**Comment by komhsgr** [comment]
https://github.com/GreekTVApp/epg-greece-cyprus

**Comment by pitsi** [comment]
Απο εκει παιρνω και εγω το xml για το epg, αλλα την ασυμπιεστη εκδοση. (το λεω και παραπανω). Η συμπιεσμενη αναφερεται και στην 1η γραμμη του m3u εδω, αλλα δεν παιζει σε μενα.

Υπαρχει καποια αλλη εφαρμογη για iptv που να δεχεται και epg για να δοκιμασω?

**Comment by komhsgr** [comment]
ΙPTV CORE

**Comment by komhsgr** [comment]
Δεν εχεις καμια απολυτος δουλεια το να ασχολησε με την λιστα greekstream tv
Eιναι για αλλη εφαρμογη, ειναι για linux, enigma 2 και εκει το epg ειναι με διαφορετικο τροπο
#EXTINF:9 group-title="ΠΑΝΕΛΛΑΔΙΚΑ" tvg-name="ΕΡΤ1" tvg-logo="https://i.imgur.com/Dd3HM0I.png",ERT1 HD

#EXTINF:9 ειναι ο κωδικος για το συγκεκριμενο καναλι.

οχι δεν θα αλλαχτουν ουτε λογοτυπα, ουτε id , ουτε display name αν ειναι δυνατον να καθομαι να ασχολουμε σε οτι σας βολευει το καθενα

**Comment by upggr** [comment]
οποιος θελει μπορει να κανει fork αυτο το repo και στο δικο του branch να κανει οτι θελει! Αν κατι το θεωρει χρησιμο η ομαδα θα κανουμε merge.

**Comment by komhsgr** [comment]
Γιαννη που εισαι αδελφε και σε ψάχνω

**Comment by pitsi** [comment]
Δεν ειπα οτι θα ασχοληθω με καμια απο τις λιστες. Το sed να ειναι καλα και τις κανω οπως θελω για παρτη μου. 
Απλα επισημανα οτι και στην αρχη, πως και η αλλη λιστα εχει λογοτυπα που παιρνονται απο το πεθαμενο πλεον domain και καλο ειναι να αλλαχτουν.

Fork κλπ δεν κανω γιατι θα πρεπει να ενημερωνω τη λιστα καθημερινα και δεν εχω τοσο χρονο. Θα μπορουσα να παρω οτι θελω απο μια αλλη λιστα με ελληνικα καναλια που υπαρχει στο github, αλλα δεν με βολευει η αλφαβητικη σειρα με την οποια ειναι βαλμενα. Θα μπορουσα ακομα και να κανω την δικη μου λιστα απο το 0 και να τα βαλω ολα οπως θελω...
Επιπλεον, θεωρω πως αρκετα εχασα το χρονο μου δοκιμαζοντας τις διαφορες εφαρμογες που λεω παραπανω. Και το συμπερασμα στο οποιο κατελληξα δεν ειναι ποια παιζει σωστα/καλυτερα με την λιστα, αλλα ποια εχει τα λιγοτερα θεματα με το epg.

Τελος, με αυτη τη συμπεριφορα με αποτρεπετε απο το να συνεισφερω στη λιστα, μιας και εχω λιγα url που αξιζουν να προστεθουν. Το θεμα κλεινει εδω.

**Comment by komhsgr** [comment]
Εχεις σοβαρο προβλημα μαγκα μιλαμε για μεγαλο κομπλεξ

**Comment by pitsi** [comment]
Λαθος. Το epg το βρηκα μονος μου (απο την 1η γραμμη της λιστας βεβαια), την αντιστοιχια των ονοματων (display name) για να παιξει σωστα το epg με ολα τα καναλια την εκανα επισης μονος μου και τελος εγω εκανα μονος μου ολο το testing για να δω που παιζει σωστα και που οχι. Εσυ αλλαξες τα προβληματικα url για τα λογοτυπα και τιποτε αλλο.

Δεν επεβαλα σε κανεναν την αλλαγη της αλλης λιστας, απλα εκανα μια προταση για αλλαγη ΠΡΙΝ μαθω που χρησιμοποιειται. Εσυ ομως απαντησες οτι δεν εχω καμια απολυτως δουλεια να ασχολουμαι με αυτη. Αν δεν δεχεσαι λοιπον κριτικη για τον κωδικα που ανεβαζεις, μιας και αναφερεις σαν επιχειρημα το οτι "δινεις κατι δωρεαν και αφιερωνεις χρονο", πραγμα που το σεβομαι γιατι και εγω το ιδιο κανω για αλλα projects, μπορεις να κλεισεις τα issue reports για αυτο εδω το repo και τερμα.
Και ναι, εχω την ιδια σταση/συμπεριφορα απεναντι σε οποιονδηποτε dev θεωρει πως αυτο που κανει εινια τελειο και δεν σηκωνει κριτικη και διορθωση.

Δεν απειλεισα κανεναν και ουτε με ενδιαφερουν οι πριβε λιστες κανενος. Και αν νομιζεις οτι μπλοφαρω οταν λεω οτι εχω url που θα μπορουσαν να μπουνε στη λιστα, μπορω να ανεβασω screenshot για να σιγουρευτεις. Δεν ειναι για κατι παρανομο, ειναι απλα εναλλακτικα url για τα υπαρχοντα καναλια της λιστας, πχ για το star.
