### ISSUE TITLE
url??

### ISSUE THREAD

**Issue by dxdydz323** [free-greek-iptv/greek-iptv#4]
Σας ευχαριστώ για την καλή δουλεια!
Επειδη κάποιες εφαρμογες ζητάνε url και όχι το m3u αρχειο, ποιο url μπορούμε να χρησιμοποιησουμε;
Το https://github.com/free-greek-iptv/greek-iptv/blob/master/android.m3u δεν κάνει για αυτό τον σκοπό.. Χρειάζεται το url που κατεβάζει το αρχείο. Πχ αυτο: http://playlist.autoiptv.net/normal.php?c=GR
 Thanks!

**Comment by komhsgr** [comment]
γιατι ανακατευεσται σε βαθος αριστερα και δεξια?

Στις Πέμ, 25 Οκτ 2018 στις 1:45 μ.μ., ο/η dxdydz323 <
notifications@github.com> έγραψε:

**Comment by 1nikolas** [comment]
Βαλε αυτο https://raw.githubusercontent.com/free-greek-iptv/greek-iptv/master/android.m3u

**Comment by dxdydz323** [comment]
Σε ευχαριστώ φίλε μου! Δουλεύει τέλεια!

**Comment by Andreasxs** [comment]
Παίδες αυτό είναι για δωρεάν nova και ote tv?

**Comment by 1nikolas** [comment]
> Παίδες αυτό είναι για δωρεάν nova και ote tv?

Οχι. Ελεύθερα μόνο εχει

**Comment by Andreasxs** [comment]
Που μπορώ να βρω ;

**Comment by 1nikolas** [comment]
> Που μπορώ να βρω ;

Εδώ πάντως οχι. Google is your friend

**Comment by komhsgr** [comment]
Ρε τι βλαμμενα κυκλοφορουν στην πιατσα?  Ποτε ειδες ρε δωρεαν οτε και νοβα και θες να δεις και τωρα?
10 ευρω το μηνα εχει η ΕΟΝ γαμω την τσιγκουνια σας και την ανοησια σας
