### ISSUE TITLE
Problem with a specific channel and replace platform 

### ISSUE THREAD

**Issue by FKOV** [free-greek-iptv/greek-iptv#46]
Hi, the channel called star ke or in greek (σταρ κεντρικής Ελλάδας) doesn't work for few days now, and there is indeed a host that can replace the broken link with 24/7 streaming and uts directly from their official dailymotion:

https://www.dailymotion.com/embed/video/x2j7kha#tab_embed.m3u8

I tried adding it but since I am a begginer on iptv I don't know which format will work on the iptv player since it didn't work. I have tried it on kodi iptv simple client and on different android iptv apps 

Thank you,keep up the good work

**Comment by FKOV** [comment]
Anyone from the dev team can respond ?

**Comment by komhsgr** [comment]
is not a problem just not working

**Comment by FKOV** [comment]
Why you don't try to import somehow the stream from the dailymotion? Because it's the official stream from the channel itself

**Comment by komhsgr** [comment]
About dailymotion 
https://www.dailymotion.com/embed/video/x2j7kha#tab_embed.m3u8
have stream link 
https://stream-05.ix7.dailymotion.com/sec(ZHW-kyIDNbzrgtZQEivCa5sPwjiPbnsnJr8WQXubAds)/dm/3/x2j7kha/s/live-2.m3u8 and change again and again 

Ant1 locked reason copyrigt 

you can see https://vod.antenna.gr/#/live/ant1

**Comment by FKOV** [comment]
@komhsgr thanks for the detailed information,  you can close the issue if you want , keep up the good work
