### ISSUE TITLE
Alpha and Open not working

### ISSUE THREAD

**Issue by nem0nxt** [free-greek-iptv/greek-iptv#6]
Channels Alpha and Open are not working.
Plz fix them.

**Comment by komhsgr** [comment]
working fine just not working to your countrie ip

Στις Δευ, 28 Ιαν 2019 στις 10:13 μ.μ., ο/η nem0nxt <notifications@github.com>
έγραψε:

**Comment by nem0nxt** [comment]
Then i am afraid it is useless for us outside Greece.

**Comment by upggr** [comment]
Thank you, perhaps we should make all the list private then

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by komhsgr** [comment]
This applies to other countries, the copyright law is strict in the
European Union. why do this only for 2 channels i dont understand and i
cant help you

Στις Τρί, 29 Ιαν 2019 στις 10:13 μ.μ., ο/η Ioannis Kokkinis <
notifications@github.com> έγραψε:

**Comment by nem0nxt** [comment]
I was just asking guys.
Thank you.
