### ISSUE TITLE
ERT channels

### ISSUE THREAD

**Issue by FPSUsername** [free-greek-iptv/greek-iptv#7]
ERT channels aren't working outside of europe, the worldwide streams doesn't exist

**Comment by komhsgr** [comment]
And what do I have to do?

**Comment by FPSUsername** [comment]
Update with working streams if you know any? AliveGR has working ERT streams but only work through the Kodi addon. If I use their m3u file, ERT doesn't work.

**Comment by upggr** [comment]
feel free to fork this repo and add extra streams if you have.
we re doing the best we can here manually.


Sent from my iPad

On Feb 24, 2019, at 23:12, FPSUsername <notifications@github.com<mailto:notifications@github.com>> wrote:


Update with working streams if you know any? AliveGR has working ERT streams but only work through the Kodi addon. If I use their m3u file, ERT doesn't work.
