### ISSUE TITLE
 formedia tv

### ISSUE THREAD

**Issue by gio299** [free-greek-iptv/greek-iptv#75]
digea.tv10.gr   afto to epg dokimastike kai doulevi apsoga gia to formedia tv
to tv10 eklise entelos kai i adeia pige sto formedia kai to epg doulevi apsoga

**Comment by gio299** [comment]
#EXTINF:-1 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-name="ddigea.aepsilonanmakthrakis.gr" tvg-logo="https://i.imgur.com/DLY2rOM.png",ED TV

to ddigea  kanto me ena  d ,gia na doulepsi to epg

**Comment by komhsgr** [comment]
Δεν δουλευει ετσι το epg πρεπει απο tv10 να αλλαξω ονομασια σε formedia tv
